num1 = input("Enter a number")
print(num1)
print(type(num1))
num2 = input("Enter a number")
print(type(num2))
print(num2)
print(type(sum))
sum = int(num1)*int(num2)
print(type(num1))
print(type(num2))
print(type(sum))
print(sum)